jms_serializer:
    handlers:
        datetime:
            default_format: 'd/m/Y'
            default_timezone: 'UTC'

    metadata:
        directories:
            DomainModel:
                namespace_prefix: Domain\Model
                path: "%kernel.root_dir%/Resources/Infrastructure/serializer/jms"